name: Issue Labeled

on:
  issues:
    types: [labeled]

permissions:
  issues: write
  pull-requests: write
  actions: read
  checks: read
  contents: read
  repository-projects: read
  statuses: read

jobs:
  issue-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: unable to reproduce
        if: "${{ github.event.label.name == 'status: can not reproduce' }}"
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }},
            
            Thank you for reporting this bug, however we are unable to reproduce the issue you described given the information we have on hand. Can you please create a fresh project that you are able to reproduce the issue in, provide clear steps to reproduce this issue, and either upload this fresh project to a new GitHub repo or compress it into a `.zip` and upload it on this issue?
            
            We would greatly appreciate your assistance with this, by working in a fresh project it will cut out any possible variables that might be unrelated.
            Please note that issues labeled with `status: can not reproduce` will be closed in 14 days if there is no activity.

            Thank you!
      - name: add random solution engineer to reproduction issues
        if: "${{ github.event.label.name == 'status: pending reproduction' }}"
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: 'derrickmehaffy, PaulBratslavsky'
          random-to: 1
      - name: comment on unsupported v3 issues
        if: "${{ github.event.label.name == 'flag: v3-unsupported' }}"
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }},

            Thank you for reporting this potential bug report, please keep in mind that we are no longer accepting bug reports unless they could be deemed high or critical severity or related to security in nature.
            The recommended action we suggest for v3 users is to utilize the various migration resources to upgrade your package from Strapi v3 to Strapi v4:

            - [Code Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/code-migration.html) and/or [Codemods project](https://github.com/strapi/codemods)
            - [Data Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/data-migration.html) and/or [Data Migration Scripts](https://github.com/strapi/migration-scripts)
            - [Plugin Migration Guide](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/plugin-migration.html)

            Please see our [Security file](https://github.com/strapi/strapi/security) for more information about supported versions.
            For now this issue is marked as closed as we do not believe this issue is Critical/High Severity nor related to security.

            Thank You
      - name: close unsupported v3 issues
        if: "${{ github.event.label.name == 'flag: v3-unsupported' }}"
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          close-reason: 'not_planned'
      # - name: alert team to critical issue
      #   if: "${{ github.event.label.name == 'severity: critical' }}"
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_CHANNEL: crisis
      #     SLACK_COLOR: bad 
      #     SLACK_TITLE: Issue marked as Critical!
      #     SLACK_USERNAME: Strapi-Alerts
      #     SLACK_FOOTER: Triggered by GitHub Actions
      - name: assign issues to Content squad project
        uses: actions/add-to-project@v0.3.0
        with:
          # project-url: https://github.com/orgs/strapi/projects/11
          project-url: https://github.com/users/derrickmehaffy/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
          labeled: "source: core:admin, source: core:content-manager, source: core:upload, source: plugin:i18n"
          label-operator: OR
      - name: assign issues to DevExp squad project
        uses: actions/add-to-project@v0.3.0
        with:
          # project-url: https://github.com/orgs/strapi/projects/13
          project-url: https://github.com/users/derrickmehaffy/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
          labeled: "source: core:content-type-builder, source: core:database, source: core:email, source: core:strapi, source: core:utils, source: plugin:graphql, source: plugin:users-permissions, source: typescript"
          label-operator: OR
      - name: assign issues to Expansions squad project
        uses: actions/add-to-project@v0.3.0
        with:
          # project-url: https://github.com/orgs/strapi/projects/4
          project-url: https://github.com/users/derrickmehaffy/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
          labeled: "source: marketplace, source: plugin:sentry, source: plugin:documentation"
          label-operator: OR